---
- name: Verify
  hosts: all

  tasks:
    - name: Check whether Google Chrome is installed
      ansible.builtin.command: google-chrome --version
      register: CHROME_INSTALLED
      changed_when: false
      ignore_errors: True

    - name: Check OS version
      ansible.builtin.command: cat /etc/redhat-release
      register: OS_VERSION
      changed_when: false

    - name: Make sure Google Chrome is installed
      ansible.builtin.debug:
        var: CHROME_INSTALLED

    - name: Show OS version
      ansible.builtin.debug:
        var: OS_VERSION
